services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=vini
      - MONGO_INITDB_ROOT_PASSWORD=vini
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8082:8082
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=vini
      - ME_CONFIG_MONGODB_ADMINPASSWORD=vini
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: {}